# Generated by Django 2.1 on 2019-05-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_friends_messages_userdata_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='userdata',
            name='image',
            field=models.ImageField(blank=True, default='download.png', upload_to='profile_image'),
        ),
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
