# Generated by Django 2.1 on 2019-05-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190511_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='image',
            field=models.ImageField(blank=True, default='profile_image/download.png', upload_to='profile_image'),
        ),
    ]
